### ISSUE TITLE
"Devolution"

### ISSUE THREAD

**Issue by RedPandaBro** [GrassyTrams/Advancement-Enhancement#3]
TIL you could get Jungle and Swamp villagers despite there being no Jungle or Swamp villages.

I think this advancement is both challenging and useful/informative

I think it needs a more tasteful name because "Devolution" has negative connotations that seem out of place in Minecraft.

Some suggestions.

"New Villager In Town"
"Not from around here"
"Cultural Expansion" or something culture-related.

Sorry for yapping on your GitHub I hope my comments find you well and you take them into consideration for any updates or hotfixes
Edit: I should mention that I enjoy your advancement pack because not only does it bring back classic Minecraft advancements it also follows Mojang principles of being either challenging or informative to features in the game. It's also less complex then other data packs and fits in well alongside vanilla advancements.

**Comment by GrassyTrams** [comment]
Devolution was more of a reference to my favourite band, but, yeah i see how that can seem insensitive. Ill change it in the next update, Which I'm unsure when thatll be, sorry.

Edit: Fixed! It is now named "Exotic Goods".
